"""Added user_image, dob, target_weight, current_weight to User table

Revision ID: 31b7245ab9fc
Revises: d3922b845cc4
Create Date: 2025-03-29 00:56:27.486807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b7245ab9fc'
down_revision = 'd3922b845cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('target_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('current_weight')
        batch_op.drop_column('target_weight')
        batch_op.drop_column('dob')
        batch_op.drop_column('user_image')

    # ### end Alembic commands ###
